### PR TITLE
Optimize Contracts Directory

### PR DESCRIPTION
**Pull request by dOrgJelli**
With this optimization (noDuplicates), the size of `./contracts` goes from 30mb to 7mb. If a project using this package then wants to reduce the size further, they can run the `noBytecode` and `noWhitespace` optimizations to reduce the size to 1.7 mb.

### CODE REVIEW

**Comment by dOrgJelli** [comment]
Will merge once I get home :)

**Comment by jellegerbrandy** [comment]
very nice <3

**Comment by jellegerbrandy** [comment]
but perhaps wait with merging this as it may not be needed (or not be needed _here_): cf. the discussion https://github.com/daostack/alchemy/pull/1264#issuecomment-561147525

**Comment by jellegerbrandy** [comment]
On further thought, this does not really solve the problem. 7M is still A LOT, and most of that contract bytecode that dependencies such as client/Alchemy do not need or want in any way.

**Comment by dOrgJelli** [comment]
Hey @jellegerbrandy, apologies for the lag on my response.

So the contract bytecode is still needed for the migration script, since it deploys new instances of some of the contracts. For example: https://github.com/daostack/migration/blob/3fea85e7de341c79e64d386efd2105597720e833/migrate-dao.js#L210

**Comment by dOrgJelli** [comment]
I just realized I was wrong @jellegerbrandy, the DAOcreator only supports deploying new DAOs with the "DaoCreator" scheme. This means that no new contracts are ever deployed, so bytecode is not required!

How about we:
1. Merge this optimization.
2. Create a utility script within this repo that outside projects can use to remove the ABI bytecode at build time.
3. Update DAOcreator to use this new migration version.

**Comment by dOrgJelli** [comment]
@jellegerbrandy I've added additional optimizations to the `optimize-abi` script / CLI for:
- Removing `bytecode` and `deployedBytecode` fields
- Removing whitespace (pretty print)

With all three optimizations (noDuplicates, noBytecode, noWhitespace) the size of the `./contracts` is now 1.7 MB.

Please note @jellegerbrandy that if we merge this, your script [here](https://github.com/daostack/client/blob/875cde39764f315bb87325ef4775e2fc9504fefa/scripts/copyABIsFromMigration.js#L29) will need to utilize the `importAbi` helper created [here](https://github.com/daostack/migration/blob/006494822babc932f05ea4be31791785d2e58a46/utils.js#L20).

**Comment by dOrgJelli** [comment]
@jellegerbrandy @ben-kaufman @orenyodfat this should be good to go, please let me know if there's anything else I can do.

**Comment by orenyodfat** [comment]
we (@dOrgJelli @jellegerbrandy and me ) agreed that in order to avoid additional updates in subgraph and alchemy client , we will add additional `optimize` directory to migration package which will be used by the daocreator.

**Comment by dOrgJelli** [comment]
@jellegerbrandy @orenyodfat @ben-kaufman so sorry this took me longer than expected to get to. I've updated the code to:
1. Have the original untouched contracts directory.
2. Have the `optimize-contracts.js` script operate on a copy of the contracts directory named `contracts-optimized`.
3. `migrate-dao` and `migrate-base` can both be called with a flag to let them know to use the `contracts-optimized` directory instead of the `contracts` directory.

Once this is merged, I'll update DAOcreator to use the latest version of this package. Once updated, DAOcreator will have a post-install script that runs the `optimize-abis` script. Then in Alchemy, it'll just have to delete the `contracts` directory during the build step to ensure it isn't included in the bundle.

**Comment by dOrgJelli** [comment]
@jellegerbrandy @ben-kaufman @orenyodfat any word on this?

**Comment by ben-kaufman** [comment]
Hi @dOrgJelli, looks good! Just a small comment. I see you added `optimizedAbis` as a flag option to the scripts. I think you should also then add support for that in the `migrate.js` file. Could you please add that (or if you want I can add it)?.

**Comment by dOrgJelli** [comment]
Hey @ben-kaufman sure thing, will add

**Comment by ben-kaufman** [comment]
@dOrgJelli thanks, looks good. Merging.

**Pull request merged**
