### PR TITLE
add networkId, windows support, ganache version, broken npm scripts

### PR DESCRIPTION
**Pull request by dkent600**
Resolves: #30 

* hardcodes networkId to potentially help stabilize the ganache db, and to be consistent with what arc.js expects in order to identify our instance of ganache  (#30)
* fixes broken npm script `migrate`
* improves windows support for scripts (#3), not including the docker commands that still don't work in windows
* fixes ganache error on migrate "Cannot read property 'pop' of undefined" by upgrading ganache-cli version

### CODE REVIEW

**Comment by dkent600** [comment]
@orenyodfat 

> please add tests

The repo has no travis test, no test framework.  There is already a ticket on that and it should be worked independently of this PR.

**Comment by orenyodfat** [comment]
> @orenyodfat
> 
> > please add tests
> 
> This repo has no travis tests, no test framework at all. There is already a ticket on that and it should be worked independently of this PR.

https://github.com/daostack/migration/blob/master/.travis.yml 
currently it is doing only linting.
please rebase your branch on top of master

**Comment by dkent600** [comment]
@orenyodfat 

> please rebase your branch on top of master

done

**Comment by orenyodfat** [comment]
@dkent600 which part of this pr support window ?

**Pull request merged**
