### PR TITLE
release 0.0.1-rc.12-v6

### PR DESCRIPTION
**Pull request by ben-kaufman**

### CODE REVIEW

**Comment by orenyodfat** [comment]
Is that just update package-lock.json ? @ben-kaufman

**Comment by ben-kaufman** [comment]
This is a fix for the previous package release

**Comment by orenyodfat** [comment]
does this suppose to fix #85  ? 
sudo npm install --global @daostack/migration@0.0.1-rc.12-v4 also fail .

**Comment by ben-kaufman** [comment]
No, it's unrelated

**Pull request merged**
