### PR TITLE
Upgrade to arc.rc3

### PR DESCRIPTION
**Pull request by dkent600**
* Upgrades to arc.rc3
* adds scripts:
  * migrate.base
  * migrate.dao
  * migrate.demo
* Resolves: #37 

**Note** the ganache addresses are updated, but not the addresses for kovan or rinkeby.  I assume those are updated as part of the NPM packaging process (correct me if wrong).

**Please** carefully review the default GenesisProtocol parameters

### CODE REVIEW

**Comment by jellegerbrandy** [comment]
I have a general question. This PR effectively breaks the deployment scripts for the old arc contracts in favor of the new ones. So, effectively, it will break everything up the stack (until that is upgraded as well). Is it worth the trouble to distinguish between migration scripts, i.e. have commands of the from "npm run migrateContracts --version rc1"?

**Comment by dkent600** [comment]
> Is it worth the trouble to distinguish between migration scripts, i.e. have commands of the from "npm run migrateContracts --version rc1"?

I can't speak for everyone who would be affected by this change.  But I might suggest that if they don't want the latest Arc then they can freeze their version of the migration package.

We want people to upgrade to the latest Arc, and don't have a lot of time to spend supporting previous versions.  So based on all that, I would vote that it is not worth the trouble.

**Comment by ben-kaufman** [comment]
Looks good but I have the same concerns as Jelle, I think we should wait at list until Arc 1 is released.

**Comment by ben-kaufman** [comment]
Should update to use RC2

**Comment by dkent600** [comment]
> How about adding tests which check that all is ok.?

First, I note that there a still no tests being run on travis, and I think that should be done in a separate PR
Second, I think the tests in migrate-demo-test.js already do a basic job of checking that the RC changes are good.

**Comment by orenyodfat** [comment]
> > How about adding tests which check that all is ok.?
> 
> First, I note that there a still no tests being run on travis, and I think that should be done in a separate PR
> Second, I think the tests in migrate-demo-test.js already do a basic job of checking that the RC changes are good.

Just add the simple test to travis.
migrate-demo-test.js just bring up a demo ..it is not a test.

**Comment by orenyodfat** [comment]
please change the version at package.json to 0.0.1-rc.3-v1

**Pull request merged**
