### PR TITLE
JSON Sanitizing

### PR DESCRIPTION
**Pull request by dOrgJelli**
Closes: https://github.com/daostack/migration/issues/171

### CODE REVIEW

**Comment by dOrgJelli** [comment]
Also as a side note, would love if this project was implemented in TypeScript. Would make integrating with it a lot less error prone, as schema + interface changes would be seen at compile time. Also it'd make the scripts a bit less error prone, for example see the bug fix in migrate-dao.js line #488

**Comment by ben-kaufman** [comment]
Thanks, looks good. Just solve the conflict please.

**Comment by dOrgJelli** [comment]
@ben-kaufman merged

**Comment by dOrgJelli** [comment]
Whoops, just saw the linting failed, it's fixed now @ben-kaufman

**Comment by dOrgJelli** [comment]
@ben-kaufman any word on this?

**Pull request merged**
